upd

diff --git a/.github/workflows/nuxtjs.yml b/.github/workflows/nuxtjs.yml
--- a/.github/workflows/nuxtjs.yml
+++ b/.github/workflows/nuxtjs.yml
@@ -31,65 +31,58 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Detect package manager
-        id: detect-package-manager
-        run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20.10.x
-          cache: ${{ steps.detect-package-manager.outputs.manager }}
-
-      - name: Setup Pages
-        uses: actions/configure-pages@v5
-        with:
-          # Automatically inject router.base in your Nuxt configuration file and set
-          # target to static (https://nuxtjs.org/docs/configuration-glossary/configuration-target/).
-          #
-          # You may remove this line if you want to manage the configuration yourself.
-          static_site_generator: nuxt
-
-      - name: Restore cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            dist
-            .nuxt
-          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
-          restore-keys: |
-            ${{ runner.os }}-nuxt-build-
-
-      - name: Install dependencies
-        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
-
-      - name: Static HTML export with Nuxt
-        run: ${{ steps.detect-package-manager.outputs.manager }} run build --preset github_pages
-        env:
-          NUXT_APP_BASE_URL: '/sf/'
-
-      - name: Upload artifact
-        uses: actions/upload-pages-artifact@v3
-        with:
-          path: ./.output/public
-
-#      - uses: JamesIves/github-pages-deploy-action@v4.6.8
+#      - name: Detect package manager
+#        id: detect-package-manager
+#        run: |
+#          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+#            echo "manager=yarn" >> $GITHUB_OUTPUT
+#            echo "command=install" >> $GITHUB_OUTPUT
+#            exit 0
+#          elif [ -f "${{ github.workspace }}/package.json" ]; then
+#            echo "manager=npm" >> $GITHUB_OUTPUT
+#            echo "command=ci" >> $GITHUB_OUTPUT
+#            exit 0
+#          else
+#            echo "Unable to determine package manager"
+#            exit 1
+#          fi
+#      - name: Setup Node
+#        uses: actions/setup-node@v4
 #        with:
-#          github_token: ${{ secrets.GITHUB_TOKEN }}
-#          branch: gh-pages
-#          folder: '.output/public'
-#          clean: true
+#          node-version: 20.10.x
+#          cache: ${{ steps.detect-package-manager.outputs.manager }}
+#
+#      - name: Setup Pages
+#        uses: actions/configure-pages@v5
+#        with:
+#          # Automatically inject router.base in your Nuxt configuration file and set
+#          # target to static (https://nuxtjs.org/docs/configuration-glossary/configuration-target/).
+#          #
+#          # You may remove this line if you want to manage the configuration yourself.
+#          static_site_generator: nuxt
+#
+#      - name: Restore cache
+#        uses: actions/cache@v4
+#        with:
+#          path: |
+#            dist
+#            .nuxt
+#          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
+#          restore-keys: |
+#            ${{ runner.os }}-nuxt-build-
+#
+#      - name: Install dependencies
+#        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+#
+#      - name: Static HTML export with Nuxt
+#        run: ${{ steps.detect-package-manager.outputs.manager }} run build --preset github_pages
+#        env:
+#          NUXT_APP_BASE_URL: '/sf/'
+#
+#      - name: Upload artifact
+#        uses: actions/upload-pages-artifact@v3
+#        with:
+#          path: ./.output/public
 
 #  # Deployment job
 #  deploy:
@@ -103,21 +96,21 @@ jobs:
 #        id: deployment
 #        uses: actions/deploy-pages@v4
 
-  # Deployment job
-  deploy:
-    # Add a dependency to the build job
-    needs: build
-    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
-    permissions:
-      pages: write      # to deploy to Pages
-      id-token: write   # to verify the deployment originates from an appropriate source
-    # Deploy to the github_pages environment
-    environment:
-      name: github_pages
-      url: ${{ steps.deployment.outputs.page_url }}
-    # Specify runner + deployment step
-    runs-on: ubuntu-latest
-    steps:
-      - name: Deploy to GitHub Pages
-        id: deployment
-        uses: actions/deploy-pages@v4
+#  # Deployment job
+#  deploy:
+#    # Add a dependency to the build job
+#    needs: build
+#    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
+#    permissions:
+#      pages: write      # to deploy to Pages
+#      id-token: write   # to verify the deployment originates from an appropriate source
+#    # Deploy to the github_pages environment
+#    environment:
+#      name: github_pages
+#      url: ${{ steps.deployment.outputs.page_url }}
+#    # Specify runner + deployment step
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Deploy to GitHub Pages
+#        id: deployment
+#        uses: actions/deploy-pages@v4
